apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-mc-nexus-pvc
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-pvc
  namespace: ci
spec:
  type: LoadBalancer
  selector:
    app: nexus-pvc
  ports:
    - port: 9002
      targetPort: 8081-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-pvc
  namespace: ci
spec:
  selector:
    matchLabels:
      app: nexus-pvc
  template:
    metadata:
      labels:
        app: nexus-pvc
    spec:
      securityContext:
        fsGroup: 200
      containers:
        - name: nexus-pvc
          image: docker.io/sonatype/nexus3
          ports:
            - containerPort: 8081
              name: 8081-tcp
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: gke-mc-nexus-pvc


