apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-mc-sonarqube-sonarqube-postgres-pvc
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sonarqube-postgres-pvc
  name: sonarqube-postgres-pvc-secret
  namespace: ci
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube-postgres-pvc
  name: sonarqube-postgres-pvc
  namespace: ci
spec:
  ports:
    - port: 5432
      targetPort: postgresport
  selector:
    app: sonarqube-postgres-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-postgres-pvc
  namespace: ci
  labels:
    name: sonarqube-postgres-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-postgres-pvc
  template:
    metadata:
      name: sonarqube-postgres-pvc
      labels:
        app: sonarqube-postgres-pvc
    spec:
      securityContext:
        fsGroup: 200
      containers:
        - image: postgres:12.1
          name: sonarqube-postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-pvc-secret
                  key: password
            - name: POSTGRES_USER
              value: sonar
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgresport
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: gke-mc-sonarqube-sonarqube-postgres-pvc
