apiVersion: v1
kind: Service
metadata:
  name: sonarqube-pvc
  namespace: ci
spec:
  type: LoadBalancer
  selector:
    app: sonarqube-pvc
  ports:
    - port: 9003
      targetPort: 9000-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube-pvc
  name: sonarqube-pvc
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-pvc
  template:
    metadata:
      labels:
        app: sonarqube-pvc
    spec:
      securityContext:
        fsGroup: 200
      containers:
        - name: sonarqube
          image: sonarqube:7.7-community
          ports:
            - containerPort: 9000
              name: 9000-tcp
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-postgres-pvc-secret
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonarqube-postgres-pvc:5432/sonar
#          volumeMounts:
#            - name: sonarqube-extensions
#              mountPath: /opt/sonarqube/extensions
#            - name: sonarqube-data
#              mountPath: /opt/sonarqube/data
#      volumes:
#        - name: sonarqube-data
#          persistentVolumeClaim:
#            claimName: gke-mc-sonarqube-data-pvc
#        - name: sonarqube-extensions
#          persistentVolumeClaim:
#            claimName: gke-mc-sonarqube-extensions-pvc
